services:
  mysql:
    image: mysql:8.0
    container_name: mysql-sync-db-dev
    environment:
      MYSQL_ROOT_PASSWORD: senha123
      MYSQL_DATABASE: mysql-sync-db-dev
      MYSQL_USER: sync
      MYSQL_PASSWORD: senha123
    ports:
      - "15606:3306"
    volumes:
      - ../mysql_data:/var/lib/mysql

volumes:
  mysql_data:
